<a href="https://colab.research.google.com/github/sonam2006-sandanshiv/microsoft-workshop/blob/main/(9%20sept)nonlinearlity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#logistic regressio threshhold ke basis pr changes
#threshold above or below it will be converted in 0 or 1
#sigmoid function 1/1+e^-z (linear fuctio passed through sigmoid)   #exponential to the power of your best fit line
#exponential se non linearity introduces
#confusion matrix
#true positvie - positive is predicted part ,true negative -  its like you think nhi hoga and nhi hua
#false +ve and false -ve (both are error)
#accuracy =(tp+tn)/tp+tn+fp+fn
#precision = tp/(tp+fp) #prediction of certain percentage #type1 error
#-ve predicted rate (recall/sensitivity)= tp/tp+fn #type 2 error
#harmonic mean f1 score= 2*(precision*sensitivity)/(pecision +sensitivity[recall ]) #imbalance ds

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("heart (3).csv")

In [ ]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

In [ ]:
df.columns

Index(['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope',
       'HeartDisease'],
      dtype='object')

In [ ]:
df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [ ]:
df.shape

(918, 12)

In [ ]:
df["HeartDisease"].value_counts()

HeartDisease
1    508
0    410
Name: count, dtype: int64

In [ ]:
df["Sex"].value_counts()

Sex
M    725
F    193
Name: count, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

In [ ]:
df["Sex"]= label .fit_transform(df["Sex"])

In [ ]:
df["ChestPainType"]= label .fit_transform(df["ChestPainType"])

In [ ]:
df["ChestPainType"]= label .fit_transform(df["ChestPainType"])

In [ ]:
obj1=df.select_dtypes('object')
obj1.columns

Index(['RestingECG', 'ExerciseAngina', 'ST_Slope'], dtype='object')

In [ ]:
encoders={}

for col in obj1:
  encoders[col]=LabelEncoder()
  df[col]=encoders[col].fit_transform(df[col])

In [ ]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,1,1,140,289,0,1,172,0,0.0,2,0
1,49,0,2,160,180,0,1,156,0,1.0,1,1
2,37,1,1,130,283,0,2,98,0,0.0,2,0
3,48,0,0,138,214,0,1,108,1,1.5,1,1
4,54,1,2,150,195,0,1,122,0,0.0,2,0

In [ ]:
##steps to build logistic regression model

In [ ]:
#f1 score should be used because
#what are the patterns due to which heart disease is present or not

In [ ]:
x=df.drop("HeartDisease",axis=1) #default axis 0 hence we have to metion
y=df["HeartDisease"]

In [ ]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.65,random_state=23)
#data if bigger then use 80%

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [ ]:
model.fit(x_train,y_train)

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [ ]:
y_pred = model.predict(x_test)

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
clf = classification_report (y_test,y_pred)
print(clf)

              precision    recall  f1-score   support

           0       0.83      0.80      0.82       138
           1       0.86      0.88      0.87       184

    accuracy                           0.85       322
   macro avg       0.85      0.84      0.84       322
weighted avg       0.85      0.85      0.85       322