<a href="https://colab.research.google.com/github/sonam2006-sandanshiv/microsoft-workshop/blob/main/12_08_26(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df= pd.read_csv("/content/clientes.csv")
df

,cod_cliente,sexo,estado_civil,dependentes,educacao,empregado,renda,renda_conjuge,emprestimo,prestacao_mensal,historico_credito,imovel,aprovacao_emprestimo
0,LP001002,Male,No,0,Graduate,No,5849,0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0,133.0,360.0,0.0,Semiurban,N

In [ ]:
df.head()

,cod_cliente,sexo,estado_civil,dependentes,educacao,empregado,renda,renda_conjuge,emprestimo,prestacao_mensal,historico_credito,imovel,aprovacao_emprestimo
0,LP001002,Male,No,0,Graduate,No,5849,0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0,141.0,360.0,1.0,Urban,Y

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   cod_cliente           614 non-null    object
 1   sexo                  601 non-null    object
 2   estado_civil          611 non-null    object
 3   dependentes           599 non-null    object
 4   educacao              614 non-null    object
 5   empregado             582 non-null    object
 6   renda                 614 non-null    int64
 7   renda_conjuge         614 non-null    object
 8   emprestimo            592 non-null    float64
 9   prestacao_mensal      600 non-null    float64
 10  historico_credito     564 non-null    float64
 11  imovel                614 non-null    object
 12  aprovacao_emprestimo  614 non-null    object
dtypes: float64(3), int64(1), object(9)
memory usage: 62.5+ KB

In [ ]:
df.shape

(614, 13)

In [ ]:
df.columns

Index(['cod_cliente', 'sexo', 'estado_civil', 'dependentes', 'educacao',
       'empregado', 'renda', 'renda_conjuge', 'emprestimo', 'prestacao_mensal',
       'historico_credito', 'imovel', 'aprovacao_emprestimo'],
      dtype='object')

In [ ]:
df.describe() #gives num val

              renda  emprestimo  prestacao_mensal  historico_credito
count    614.000000  592.000000         600.00000         564.000000
mean    5403.459283  146.412162         342.00000           0.842199
std     6109.041673   85.587325          65.12041           0.364878
min      150.000000    9.000000          12.00000           0.000000
25%     2877.500000  100.000000         360.00000           1.000000
50%     3812.500000  128.000000         360.00000           1.000000
75%     5795.000000  168.000000         360.00000           1.000000
max    81000.000000  700.000000         480.00000           1.000000

In [ ]:
df.describe(exclude= "number")

,cod_cliente,sexo,estado_civil,dependentes,educacao,empregado,renda_conjuge,imovel,aprovacao_emprestimo
count,614,601,611,599,614,582,614,614,614
unique,614,2,2,4,2,2,287,3,2
top,LP002990,Male,Yes,0,Graduate,No,0,Semiurban,Y
freq,1,489,398,345,480,500,273,233,422