<a href="https://colab.research.google.com/github/sonam2006-sandanshiv/microsoft-workshop/blob/main/linear%20models(8sept).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#simple regression = y =W0+w1x
#weights are asssigned to decide the significance
#multiple regression y=wo+w1x1+....wnxn
#point whre it touches y is y intercept
#diffeence bwn predicted and actuaal value error
#coeff is weight
#wegiths and bias
#what is trainable parameter
#individual error = lost function , overall error= cost function
#linearity relation between x and y
#regression always of independent ad dependent (i/p and o/p)
#correlatio can be between any two col (can be anything)
#gradient decent  - overall error (cost function) ko low krne ke liye use hota hai ,getting down from the slope
#leARNING rate - going from one point to other types - big learning rate(zig-zag, no control,we may or may not reach grading decent,fast),too small, just right (its done by changing weights)
#decaying learning raTE = learning rate km km hote jata hai when reaching the global min (as error km km hote ja rhaa) , its the answer for learning rate which is just right

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("housing.csv")

In [ ]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [ ]:
df.columns

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='object')

In [ ]:
df.describe()

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

In [ ]:
df.shape

(545, 13)

In [ ]:
x= df.drop("price",axis=1)
#axis=1 is for col

x.head()

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,7420,4,2,3,1,0,0,0,1,2,1,0
1,8960,4,4,4,1,0,0,0,1,3,0,0
2,9960,3,2,2,1,0,1,0,0,2,1,1
3,7500,4,2,2,1,0,1,0,1,3,1,0
4,7420,4,1,2,1,1,1,0,1,2,0,0

In [ ]:
y=df["price"]

In [ ]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

In [ ]:
df["mainroad"].value_counts() #before converting categeorical data  #this was yes no and their count

mainroad
1    468
0     77
Name: count, dtype: int64

In [ ]:
df ["mainroad"] = label.fit_transform(df["mainroad"])

In [ ]:
df["mainroad"].value_counts()

mainroad
1    468
0     77
Name: count, dtype: int64

In [ ]:
obj1=df.select_dtypes('object')
obj1.columns

Index([], dtype='object')

In [ ]:
encoders={}

for col in obj1:
  encoders[col]=LabelEncoder()
  df[col]=encoders[col].fit_transform(df[col])

In [ ]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,0
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,0
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,1
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,0
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,0

In [ ]:
#model making

In [ ]:
from sklearn.linear_model import LinearRegression
model= LinearRegression()

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=23)

In [ ]:
df.shape

(545, 13)

In [ ]:
x_train.shape

(381, 12)

In [ ]:
(381/545)*100

69.90825688073394

In [ ]:
x_test.shape

(164, 12)

In [ ]:
(164/545)*100

30.091743119266056

In [ ]:
model.fit(x_train,y_train)

LinearRegression()

In [ ]:
y_pred = model.predict(x_test)

In [ ]:
y_pred.shape

(164,)

In [ ]:
y_test.shape

(164,)

In [ ]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [ ]:
mse=mean_squared_error(y_test,y_pred)

In [ ]:
mse

1037405244108.5101

In [ ]:
rmse = np.sqrt(mse)

In [ ]:
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

In [ ]:
rmse

np.float64(1018530.9244733368)